version: "3.6"

volumes:
  sonarqube: {}
  postgresql: {}

networks:
  jenkins_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.5.0/24

services:
  sonarqube:
    image: sonarqube:community
    hostname: sonar.magedu.com
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube:/opt/sonarqube
    ports:
      - "9000:9000"
    networks:
      jenkins_net:
        ipv4_address: 172.31.5.2
        aliases:
          - sonar
          - sonarqube
          - sonarqube.magedu.com
    restart: always

  db:
    image: postgres:12
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
    networks:
      jenkins_net:
        ipv4_address: 172.31.5.3
    restart: always
