version: '3.6'

volumes:
  ssh_agent01_data: {}
  ssh_agent02_data: {}

networks:
  jenkins_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.9.0/24

services:
  ssh-agent01:
    image: jenkins/ssh-agent:jdk11
    hostname: ssh-agent01.magedu.com
    #user: jenkins
    environment:
      TZ: Asia/Shanghai
      #JENKINS_AGENT_HOME: /home/jenkins
      JENKINS_AGENT_SSH_PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDImM93HAyMF5eJ8QsyaMkiON0h8T0hLXfohCm734Gd6b/9D/Nx5poaUvrfJgvnky3LdogzXwLUmdVcy588iTCt1u0gTIJ67YbSDUtdZHn6I2UMAvVmt6x7t+ZjTS/d1CJEX/mWOISIgDzxBQz1a9HstkfIH4MQCjdxaOmAFR65H8woNJ+QBFcBf60vRN9bXtfQDg2U7pFHdcNCjUs0HhnPsx6QtLXPErAndVFULjLPJLzD8zO+vCyqJbSFlbyD298lK7QmGd6DbYuHHZjzArRZ9rrHruFXW8P7weP+jIAkrmm72vx0WsvTf9T/Vzk4Bd9lHM8f4gu4/LheHwvhMMUk9ergqY06zty8yJC70SHw1ZJ2BzuKpgbhPugPRzpbzRhB2F4KkrGgRs91s/M/jCs4NNC7ACk+viKx0LFrydWsCy37uQRnUNFSv3dxgxwL4IIpefyZmfETGGpIgtCXbL9zPetH8OUKXf+cu3cWYeHbQfiiNy/FayGXN+peGVFhLWc= root@lab03.magedu.com
      # SSH PRIVATE KEY and PUBLIC KEY is generated by you.
    networks:
      jenkins_net:
        ipv4_address: 172.31.9.21
        aliases:
          - ssh-slave01
          - ssh-agent01
    ports:
      - "22022:22"
    extra_hosts:
      - "jenkins.magedu.com:${JENKINS_HOST_IP}"
    #restart: always

  ssh-agent02:
    image: jenkins/ssh-agent:jdk11
    hostname: ssh-agent02.magedu.com
    #user: jenkins
    environment:
      TZ: Asia/Shanghai
      #JENKINS_AGENT_HOME: /home/jenkins
      JENKINS_AGENT_SSH_PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDImM93HAyMF5eJ8QsyaMkiON0h8T0hLXfohCm734Gd6b/9D/Nx5poaUvrfJgvnky3LdogzXwLUmdVcy588iTCt1u0gTIJ67YbSDUtdZHn6I2UMAvVmt6x7t+ZjTS/d1CJEX/mWOISIgDzxBQz1a9HstkfIH4MQCjdxaOmAFR65H8woNJ+QBFcBf60vRN9bXtfQDg2U7pFHdcNCjUs0HhnPsx6QtLXPErAndVFULjLPJLzD8zO+vCyqJbSFlbyD298lK7QmGd6DbYuHHZjzArRZ9rrHruFXW8P7weP+jIAkrmm72vx0WsvTf9T/Vzk4Bd9lHM8f4gu4/LheHwvhMMUk9ergqY06zty8yJC70SHw1ZJ2BzuKpgbhPugPRzpbzRhB2F4KkrGgRs91s/M/jCs4NNC7ACk+viKx0LFrydWsCy37uQRnUNFSv3dxgxwL4IIpefyZmfETGGpIgtCXbL9zPetH8OUKXf+cu3cWYeHbQfiiNy/FayGXN+peGVFhLWc= root@lab03.magedu.com
      # SSH PRIVATE KEY and PUBLIC KEY is generated by you.
    networks:
      jenkins_net:
        ipv4_address: 172.31.9.22
        aliases:
          - ssh-slave02
          - ssh-agent02
    ports:
      - "22122:22"
    extra_hosts:
      - "jenkins.magedu.com:${JENKINS_HOST_IP}"
    #restart: always
